#!/bin/bash
set -e

. script/options.bash

options="--rm"
echo $@ | grep '\--no-cache' &> /dev/null && options="$options --no-cache" || :

echo "Creating opencontrol/compliance-masonry image"
docker build $options -f dockerfiles/dockerfile-compliance -t ${COMPLIANCE_IMAGE} .

echo "Show all docker images"
docker images

echo
echo "WARN: you should docker tag the images."
echo
